pipeline{
    agent{
        docker{
            image 'maven:3-alpine'
            args '-v/root/.m2:/root/.m2'
        }
    }
        stages{
            stage('Git-Checkout')
            {
              steps{
                     git 'https://github.com/sreelakshmi665/SamplePipe.git'
                }
            }
             stage('Validate')
        {
            steps{
              sh 'mvn -f SamplePipe/pom.xml validate'
            }
        }
        stage('Compile')
        {
            steps{
               sh 'mvn -f SamplePipe/pom.xml compile'
            }
        }
        stage('Test')
        {
            steps{
                sh 'mvn -f SamplePipe/pom.xml test'
            }
        }
        stage('Package')
        {
            steps{
               sh 'mvn -f SamplePipe/pom.xml package'
            }
        }
        stage('Verify')
        {
            steps{
               sh 'mvn -f SamplePipe/pom.xml verify'
            }
        }
        stage('Install')
        {
            steps{
                sh 'mvn -f SamplePipe/pom.xml install'
            }
        }
            
            
           
        }
}
